---
- name: Fail if no FS-path or URL to image is provided
  ansible.builtin.fail:
    msg: "No path or url to ova is provided. Please set 'vm_path_to_ova' or 'ci_image_name' and consult the 'README.md'."
  when: (vm_path_to_ova is not defined or vm_path_to_ova|length==0) and (ci_image_name is not defined)

- name: Verify that required parameters are set
  assert:
    that:
      - '{{ item.key }} is defined'
      - '{{ item.key }} | length > 0'
  with_items:
    - { key: cloudinit_fqdn }
    - { key: vcenter_hostname }
    - { key: vcenter_username }
    - { key: vcenter_password }
    - { key: vcenter_datacenter }
    - { key: vcenter_cluster }
    - { key: vm_disk_datastore }
    - { key: vm_net_name }

- name: Verify that required parameters are set - bool
  assert:
    that:
      - '{{ item.key }} is defined'
      - '{{ item.key }} is boolean'
  with_items:
    - { key: vcenter_validate_certs }
...