---
- name: Create VM
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vcenter_destination_folder }}" # folder: "/{{ dc }}/vm"
    name: "{{ cloudinit_fqdn }}"
    state: "{{ vm_state }}"
    guest_id: "{{ vm_guestid }}"
    datastore: "{{ vm_disk_datastore }}"
    hardware:
      memory_mb: "{{ vm_hw_ram_mb }}"
      num_cpus: "{{ vm_hw_cpu_n }}"
      scsi: "{{ vm_hw_scsi }}"
      hotadd_cpu: true
      hotremove_cpu: true
      hotadd_memory: true
    networks:
      - name: "{{ vm_net_name }}"
        device_name: "{{ vm_net_device_type }}"
        #  type: dhcp
      # - name: "{{ vm_net_name }}"
      #   device_name: "{{ vm_net_device_type }}"
      #   type: static
      #   device_type: vmxnet3
      #   ip: “{{ vm_ip }}”
      #   netmask: “{{ netmask }}”
      #   dns_servers:
      #     — “{{ dns_server1 }}”
      #     — “{{ dns_server2 }}”
      #   gateway: “{{ network_gateway }}”
      #   register: static_vm
      #   when: network_type == 'static'
    # wait_for_ip_address: yes
    annotation: “{{ vm_notes | default('Provisioned by ansible') }}”
  delegate_to: localhost
  when: "'.vmdk' in ci_image_name"
...
