---
# source: https://kb.vmware.com/s/article/1028943
# only the root user is permitted to connect sothis is untestd please report the success
- name: Convert vmware-player vmdk to esxi vmdk
  ansible.builtin.command:
    cmd: /bin/vmkfstools -i /vmfs/volumes/{{ vm_disk_datastore }}/{{ cloudinit_fqdn }}/{{ cloudinit_fqdn }}.vmware-player.vmdk /vmfs/volumes/{{ vm_disk_datastore }}/{{ cloudinit_fqdn }}/{{ cloudinit_fqdn }}.vmdk  # noqa yaml
  delegate_to: "{{ vcenter_cluster }}"
  when: "'.vmdk' in ci_image_name"
...
