---
- name: Start VM
  tags: Start-vm
  vmware_guest:
    hostname: "{{ vcenter_hostname | default(omit) }}"
    username: "{{ vcenter_username | default(omit) }}"
    password: "{{ vcenter_password | default(omit) }}"
    validate_certs: "{{ vcenter_validate_certs | default(omit) }}"
    name: "{{ cloudinit_fqdn }}"
    state: poweredon
    wait_for_ip_address: true
  delegate_to: localhost
...
